---
- hosts: newservers
  remote_user: root
  roles:
   - role: new
  vars:
  - interfaces:
    - { name: 'eth0', ip_addr: '192.168.1.101', netmask: '255.255.255.0', gtw: '192.168.1.1', dns1: '192.168.1.3',  dns2: '192.168.1.1', domaine: 'moufi.net' }
   # - { name: 'eth1', ip_addr: '192.168.3.100', netmask: '255.255.255.0'}
  - name: docker2
