---
# tasks file for reversibilite
- include_tasks: apache.yaml
  when: ansible_os_family == "RedHat"

- name: Suppression des fichiers de script mysql
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/lbn/mysql/script/mysqlInstance
    - /usr/local/linkbynet/script/bin/BackupMySQL.sh
    - /usr/local/linkbynet/script/bin/mysql-list
    - /usr/local/linkbynet/script/bin/mysqltuner.pl
    - /usr/local/linkbynet/script/bin/tuning-primer.sh
    - /usr/local/linkbynet/script/sbin/snapshot.pl
    - /usr/local/linkbynet/script/sbin/RestoreMySQL.pl
    - /etc/lbn/mysql/script/clustercheck
    - /etc/lbn/garbd/script/garbdInstance
  become: yes

- name: Suppression des fichiers de script memcached
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/lbn/memcached/script/memcachedInstance
    - /etc/lbn/memcached/script/memcachedListInstances"
  become: yes

- name: Suppression des fichiers de script tomcat
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/lbn/tomcat/script/tomcatInstance
    - /etc/lbn/tomcat/tpl
  become: yes

- name: Suppression des fichiers de script varnish
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/lbn/varnish/script/varnishInstance
  become: yes

- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  become: yes

- name: Remove lbn packages in Redhat derivatives
  yum: name='{{ item }}' state=absent
  with_items: '{{lbn_pkgs}}'
  when: ansible_os_family == 'RedHat'
  become: yes

- name: Remove lbn packages in Debian derivatives
  apt: name='{{ item }}' state=absent update_cache=yes
  with_items: '{{lbn_pkgs}}'
  when: ansible_os_family == 'Debian'
  become: yes

- name: Delete files in  /home/lbn
  shell: find /home/lbn/  -type f -mindepth 2 ! -name .bash* ! -name authorized_keys ! name known_hosts ! -name .profile --delete
  become: yes

- name: Delete history
  shell: find /home/lbn/  -type f -mindepth 2 ! -name .bash_history  -exec  cat /dev/null > {} \;
  become: yes
