---
- name: Create interface 
  template: src=deb_int.j2 dest="{{ deb_network_sysconfig }}"
  when:
  - apply
  notify: restart network
  tags:
  - deb

- name: Apply settings NOW
  service: name=network state=restarted
  when:
  - apply_now


- name: Create interface temp
  template: src=deb_int.j2 dest="{{ tmp_dir }}/interfaces"
  when:
  - not apply
  tags:
  - deb
